=== ttezer/turkiye-harita-verisi/schema/yerlesim.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.org/turkiye_map/schema/yerlesim.schema.json",
  "title": "Yerlesim",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "level",
    "type",
    "parent_id",
    "province_id",
    "district_id",
    "province_name",
    "district_name",
    "name",
    "name_ascii",
    "slug",
    "source",
    "source_file",
    "source_row"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^TR-Y-[0-9]{2}-[0-9]{3}-[MK]-[0-9]{4}$"
    },
    "level": {
      "const": "yerlesim"
    },
    "type": {
      "enum": [
        "mahalle",
        "koy"
      ]
    },
    "parent_id": {
      "type": "string",
      "pattern": "^TR-D-[0-9]{2}-[0-9]{3}$"
    },
    "province_id": {
      "type": "string",
      "pattern": "^TR-P-[0-9]{2}$"
    },
    "district_id": {
      "type": "string",
      "pattern": "^TR-D-[0-9]{2}-[0-9]{3}$"
    },
    "province_name": {
      "type": "string",
      "minLength": 1
    },
    "district_name": {
      "type": "string",
      "minLength": 1
    },
    "administrative_unit_name": {
      "type": "string",
      "minLength": 1
    },
    "administrative_unit_name_ascii": {
      "type": "string",
      "minLength": 1
    },
    "is_district_center_unit": {
      "type": "boolean"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "name_ascii": {
      "type": "string",
      "minLength": 1
    },
    "slug": {
      "type": "string",
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "source": {
      "const": "e-icisleri-mulki-idare-bolumleri"
    },
    "source_file": {
      "type": "string",
      "minLength": 1
    },
    "source_row": {
      "type": "integer"
    }
  }
}

=== ttezer/turkiye-harita-verisi/dist/json/yerlesimler-by-district/TR-D-25-019.json
[
  {
    "id": "TR-Y-25-019-M-0001",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Altınçanak",
    "name_ascii": "altincanak",
    "slug": "altincanak-mahalle-uzundere-erzurum-0001",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11476
  },
  {
    "id": "TR-Y-25-019-M-0002",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Balıklı",
    "name_ascii": "balikli",
    "slug": "balikli-mahalle-uzundere-erzurum-0002",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11477
  },
  {
    "id": "TR-Y-25-019-M-0003",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Çağlayan",
    "name_ascii": "caglayan",
    "slug": "caglayan-mahalle-uzundere-erzurum-0003",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11479
  },
  {
    "id": "TR-Y-25-019-M-0004",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Çamlıyamaç",
    "name_ascii": "camliyamac",
    "slug": "camliyamac-mahalle-uzundere-erzurum-0004",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11480
  },
  {
    "id": "TR-Y-25-019-M-0005",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Çaybaşı",
    "name_ascii": "caybasi",
    "slug": "caybasi-mahalle-uzundere-erzurum-0005",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11469
  },
  {
    "id": "TR-Y-25-019-M-0006",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Cevizli",
    "name_ascii": "cevizli",
    "slug": "cevizli-mahalle-uzundere-erzurum-0006",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11478
  },
  {
    "id": "TR-Y-25-019-M-0007",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Cömertler",
    "name_ascii": "comertler",
    "slug": "comertler-mahalle-uzundere-erzurum-0007",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11468
  },
  {
    "id": "TR-Y-25-019-M-0008",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Dikyar",
    "name_ascii": "dikyar",
    "slug": "dikyar-mahalle-uzundere-erzurum-0008",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11481
  },
  {
    "id": "TR-Y-25-019-M-0009",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Erikli",
    "name_ascii": "erikli",
    "slug": "erikli-mahalle-uzundere-erzurum-0009",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11470
  },
  {
    "id": "TR-Y-25-019-M-0010",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Gölbaşı",
    "name_ascii": "golbasi",
    "slug": "golbasi-mahalle-uzundere-erzurum-0010",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11482
  },
  {
    "id": "TR-Y-25-019-M-0011",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Kirazlı",
    "name_ascii": "kirazli",
    "slug": "kirazli-mahalle-uzundere-erzurum-0011",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11483
  },
  {
    "id": "TR-Y-25-019-M-0012",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Merkez",
    "name_ascii": "merkez",
    "slug": "merkez-mahalle-uzundere-erzurum-0012",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11472
  },
  {
    "id": "TR-Y-25-019-M-0013",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Muratefendi",
    "name_ascii": "muratefendi",
    "slug": "muratefendi-mahalle-uzundere-erzurum-0013",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11473
  },
  {
    "id": "TR-Y-25-019-M-0014",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Pehlivanlı",
    "name_ascii": "pehlivanli",
    "slug": "pehlivanli-mahalle-uzundere-erzurum-0014",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11467
  },
  {
    "id": "TR-Y-25-019-M-0015",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Sapaca",
    "name_ascii": "sapaca",
    "slug": "sapaca-mahalle-uzundere-erzurum-0015",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11484
  },
  {
    "id": "TR-Y-25-019-M-0016",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Seyitefendi",
    "name_ascii": "seyitefendi",
    "slug": "seyitefendi-mahalle-uzundere-erzurum-0016",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11474
  },
  {
    "id": "TR-Y-25-019-M-0017",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Ulubağ",
    "name_ascii": "ulubag",
    "slug": "ulubag-mahalle-uzundere-erzurum-0017",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11485
  },
  {
    "id": "TR-Y-25-019-M-0018",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Uzundere",
    "name_ascii": "uzundere",
    "slug": "uzundere-mahalle-uzundere-erzurum-0018",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11471
  },
  {
    "id": "TR-Y-25-019-M-0019",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-25-019",
    "province_id": "TR-P-25",
    "district_id": "TR-D-25-019",
    "province_name": "Erzurum",
    "district_name": "Uzundere",
    "name": "Yayla",
    "name_ascii": "yayla",
    "slug": "yayla-mahalle-uzundere-erzurum-0019",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 11475
  }
]

=== ttezer/turkiye-harita-verisi/dist/json/yerlesimler-by-district/TR-D-42-008.json
[
  {
    "id": "TR-Y-42-008-M-0001",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Adakasım",
    "name_ascii": "adakasim",
    "slug": "adakasim-mahalle-celtik-konya-0001",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19265
  },
  {
    "id": "TR-Y-42-008-M-0002",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Bahçelievler",
    "name_ascii": "bahcelievler",
    "slug": "bahcelievler-mahalle-celtik-konya-0002",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19273
  },
  {
    "id": "TR-Y-42-008-M-0003",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Bahçesaray",
    "name_ascii": "bahcesaray",
    "slug": "bahcesaray-mahalle-celtik-konya-0003",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19276
  },
  {
    "id": "TR-Y-42-008-M-0004",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Doğanyurt",
    "name_ascii": "doganyurt",
    "slug": "doganyurt-mahalle-celtik-konya-0004",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19266
  },
  {
    "id": "TR-Y-42-008-M-0005",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Fatih",
    "name_ascii": "fatih",
    "slug": "fatih-mahalle-celtik-konya-0005",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19274
  },
  {
    "id": "TR-Y-42-008-M-0006",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Gökpınar",
    "name_ascii": "gokpinar",
    "slug": "gokpinar-mahalle-celtik-konya-0006",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19271
  },
  {
    "id": "TR-Y-42-008-M-0007",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Honamlı",
    "name_ascii": "honamli",
    "slug": "honamli-mahalle-celtik-konya-0007",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19278
  },
  {
    "id": "TR-Y-42-008-M-0008",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "İshakuşağı",
    "name_ascii": "ishakusagi",
    "slug": "ishakusagi-mahalle-celtik-konya-0008",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19267
  },
  {
    "id": "TR-Y-42-008-M-0009",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Karşıyaka",
    "name_ascii": "karsiyaka",
    "slug": "karsiyaka-mahalle-celtik-konya-0009",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19277
  },
  {
    "id": "TR-Y-42-008-M-0010",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Kaşören",
    "name_ascii": "kasoren",
    "slug": "kasoren-mahalle-celtik-konya-0010",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19268
  },
  {
    "id": "TR-Y-42-008-M-0011",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Küçükhasan",
    "name_ascii": "kucukhasan",
    "slug": "kucukhasan-mahalle-celtik-konya-0011",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19272
  },
  {
    "id": "TR-Y-42-008-M-0012",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Selçuk",
    "name_ascii": "selcuk",
    "slug": "selcuk-mahalle-celtik-konya-0012",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19275
  },
  {
    "id": "TR-Y-42-008-M-0013",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Torunlar",
    "name_ascii": "torunlar",
    "slug": "torunlar-mahalle-celtik-konya-0013",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19269
  },
  {
    "id": "TR-Y-42-008-M-0014",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-008",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-008",
    "province_name": "Konya",
    "district_name": "Çeltik",
    "name": "Yukarı Aliçomak",
    "name_ascii": "yukari alicomak",
    "slug": "yukari-alicomak-mahalle-celtik-konya-0014",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19270
  }
]

=== ttezer/turkiye-harita-verisi/dist/json/yerlesimler-by-district/TR-D-42-010.json
[
  {
    "id": "TR-Y-42-010-M-0001",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Arapözü",
    "name_ascii": "arapozu",
    "slug": "arapozu-mahalle-derbent-konya-0001",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19337
  },
  {
    "id": "TR-Y-42-010-M-0002",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Camiikebir",
    "name_ascii": "camiikebir",
    "slug": "camiikebir-mahalle-derbent-konya-0002",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19339
  },
  {
    "id": "TR-Y-42-010-M-0003",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Çiftliközü",
    "name_ascii": "ciftlikozu",
    "slug": "ciftlikozu-mahalle-derbent-konya-0003",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19338
  },
  {
    "id": "TR-Y-42-010-M-0004",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Değiş",
    "name_ascii": "degis",
    "slug": "degis-mahalle-derbent-konya-0004",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19332
  },
  {
    "id": "TR-Y-42-010-M-0005",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Derbenttekke",
    "name_ascii": "derbenttekke",
    "slug": "derbenttekke-mahalle-derbent-konya-0005",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19333
  },
  {
    "id": "TR-Y-42-010-M-0006",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Güney",
    "name_ascii": "guney",
    "slug": "guney-mahalle-derbent-konya-0006",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19340
  },
  {
    "id": "TR-Y-42-010-M-0007",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Güneyköy",
    "name_ascii": "guneykoy",
    "slug": "guneykoy-mahalle-derbent-konya-0007",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19334
  },
  {
    "id": "TR-Y-42-010-M-0008",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Hacıahmet",
    "name_ascii": "haciahmet",
    "slug": "haciahmet-mahalle-derbent-konya-0008",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19341
  },
  {
    "id": "TR-Y-42-010-M-0009",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Karalar",
    "name_ascii": "karalar",
    "slug": "karalar-mahalle-derbent-konya-0009",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19344
  },
  {
    "id": "TR-Y-42-010-M-0010",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Mülayim",
    "name_ascii": "mulayim",
    "slug": "mulayim-mahalle-derbent-konya-0010",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19335
  },
  {
    "id": "TR-Y-42-010-M-0011",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Saraypınar",
    "name_ascii": "saraypinar",
    "slug": "saraypinar-mahalle-derbent-konya-0011",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19336
  },
  {
    "id": "TR-Y-42-010-M-0012",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Süleyman",
    "name_ascii": "suleyman",
    "slug": "suleyman-mahalle-derbent-konya-0012",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19343
  },
  {
    "id": "TR-Y-42-010-M-0013",
    "level": "yerlesim",
    "type": "mahalle",
    "parent_id": "TR-D-42-010",
    "province_id": "TR-P-42",
    "district_id": "TR-D-42-010",
    "province_name": "Konya",
    "district_name": "Derbent",
    "name": "Yukarı",
    "name_ascii": "yukari",
    "slug": "yukari-mahalle-derbent-konya-0013",
    "source": "e-icisleri-mulki-idare-bolumleri",
    "source_file": "Mahalle_Listesi.xls",
    "source_row": 19342
  }
]
